apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        resources:
          requests:
            memory: "1Gi"
            cpu: "100m"
          limits:
            memory: "1.5Gi"
            cpu: "300m"
        env:
        - name: discovery.type
          value: single-node
